# Site settings
title: "test repo"
email: "hassenbentanfous@gmail.com"
description: "test "
#baseurl: "http://hbt.github.io/"
url: "http://hbt.github.io/testrepo"
future: true

# Build settings
markdown: asciidoctor
permalink: pretty
